version: '3.7'
services:
  backend:
    build: 
      context: backend-python/
      dockerfile: Dockerfile
    init: true
    networks:
    - application-bak
  mysqldb:
    build: 
      context: mysqldb/
      dockerfile: Dockerfile
    init: true
    networks:
    - application-bak
  frontend:
    build: 
      context: frontend-node/
      dockerfile: Dockerfile
    init: true
    networks:
    - application-fr
    - application-bak
    ports:
    - "9091-9095:8080"
    depends_on:
    - backend
    - mysqldb  
networks:
  application-fr:
    name: application-fr
  application-bak:  
    name: application-bak
